# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  mywebapi:
    image: mywebapi
    build:
      context: .
      dockerfile: src/MyWebApi/Dockerfile
    ports:
      - 5067:5067
